#!/bin/bash
if [ "$WAIT_DB" != true ]; then
    log INFO No estoy esperando un servidor postgres
    exit 0
fi

log INFO Esperando hasta que Postgres este escuchando $PGHOST...
while true; do
    psql --list > /dev/null 2>&1 && break
    sleep 1
done
