#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from glob import iglob

from andamiolib import ADDONS_DIR, ADDONS_YAML, SRC_DIR, addons_config, logger

logger.info("Linkeando todos los addons de %s en %s", ADDONS_YAML, ADDONS_DIR)

# Eliminar todos los enlaces en el directorio addons
for link in iglob(os.path.join(ADDONS_DIR, "*")):
    os.remove(link)
# Agregar nuevos enlaces
for addon, repo in addons_config():
    src = os.path.relpath(os.path.join(SRC_DIR, repo, addon), ADDONS_DIR)
    dst = os.path.join(ADDONS_DIR, addon)
    os.symlink(src, dst)
    logger.debug("Vinculado %s en %s", src, dst)
