#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import sys

from andamiolib import logger

from plumbum import BG, local
from plumbum.cmd import geoipupdate

GEOIP_ACCOUNT_ID = local.env["GEOIP_ACCOUNT_ID"]
GEOIP_LICENSE_KEY = local.env["GEOIP_LICENSE_KEY"]

if GEOIP_ACCOUNT_ID not in {"", "0"} and GEOIP_LICENSE_KEY not in {"", "0"}:
    # ver https://dev.maxmind.com/geoip/geoipupdate/
    logger.info("Activando actualizaciones de GeoIP/GeoLite2")
    logger.info(
        "Este producto incluye datos GeoLite2 creados por MaxMind, "
        "Disponible de https://www.maxmind.com"
    )
    # Obtener la configuración actual de GeoIP
    geoip_file = local.path("/opt/odoo/auto/geoip/GeoIP.conf")
    geoip_conf = geoip_file.read()
    # Parchelo con las claves de cuenta y licencia proporcionadas
    geoip_conf = re.sub(
        r"(^|\n)AccountID\s*[^\n]*(\n|$)",
        "\\1AccountID {}\\2".format(GEOIP_ACCOUNT_ID),
        geoip_conf,
    )
    geoip_conf = re.sub(
        r"(^|\n)LicenseKey\s*[^\n]*(\n|$)",
        "\\1LicenseKey {}\\2".format(GEOIP_LICENSE_KEY),
        geoip_conf,
    )
    geoip_file.write(geoip_conf)
    # Ejecute la actualización de geoip en segundo plano para
    # asegurarse de que no bloquea el inicio de Odoo
    geoipupdate & BG(stdout=sys.stdout, stderr=sys.stderr)
