#!/bin/bash
set -e

if [ "$COMPILE" != true ]; then
    log WARNING No se esta compilando codigo Python
    exit 0
fi

log INFO Compilando todo el codigo Python en /opt/odoo
python -m compileall -q /opt/odoo
