#!/bin/bash
set -e
src=/opt/odoo/custom/src/odoo
dst=/usr/local/bin/odoo
log INFO Instalando Odoo desde $src

# Para el desarrollo, puede evitar instalar Odoo para acelerar la compilación
if [ "$PIP_INSTALL_ODOO" == true ]; then
    args="--no-cache-dir"
    # Odoo <= v8 las dependencias pueden fallar en la instalación, por eso no las usamos
    if [ "$ODOO_VERSION" == "7.0" -o "$ODOO_VERSION" == "8.0" ]; then
        args="$args --no-deps"
    fi
    pip install $args --editable $src

    # Hacer que las versiones 7.0 a 9.0 tengan un ejecutable `odoo`
    if [ "$ODOO_VERSION" == "7.0" ]; then
        ln -s /usr/local/bin/openerp-server $dst
    elif [ "$ODOO_VERSION" == "8.0" -o "$ODOO_VERSION" == "9.0" ]; then
        ln -s $dst.py $dst
    fi
else
    log WARNING A ciegas symlinkeado del ejecutable de odoo
    bin=$src/odoo-bin
    # No se puede verificar la existencia de scripts y vincularlos a todos:
    # ¡probablemente todavía no existan en el momento de la compilación!
    # Simplemente verifique la versión de Odoo y actúe correctamente.
    if [ "$ODOO_VERSION" == "7.0" ]; then
        bin=$src/openerp-server
        ln -s /opt/odoo/custom/src/odoo/openerp-server /usr/local/bin/
    elif [ "$ODOO_VERSION" == "8.0" -o "$ODOO_VERSION" == "9.0" ]; then
        bin=$src/odoo.py
        ln -s /opt/odoo/custom/src/odoo/openerp-{gevent,server} /usr/local/bin/
    fi
    ln -s $bin $dst
fi
