name: Dued Provision

on:
  # schedule:
  #    - cron: "0 0 * * *"
  push:
    branches:
      - "[0-9]+.0"
      - "[0-9]+.0-*"
    paths:
      - "**/workflows/**"
      - "**/resources/**"
      - "Dockerfile"

  # le permite ejecutar este flujo de trabajo manualmente desde la pestaña de acción
  workflow_dispatch:

env:
  HUB_BASE: dued # docker registry
  GIT_BASE: ghcr.io/dued # github repo

jobs:
  build:
    name: Construir imágenes
    runs-on: ubuntu-latest
    steps:
      - name: Verificación
        uses: actions/checkout@v4

      - name: Inyectar slug/Variables cortas
        uses: rlespinasse/github-slug-action@v4

        # Gestión automática de etiquetas y especificación de formato de imagen OCI para etiquetas
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # lista de imágenes de Docker para usar como nombre base para las etiquetas
          images: |
            ${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}

      - name: Instalar QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Instala Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login al Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construye y empuja la imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags:
            ${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG
            }}:sha-${{ env.GITHUB_SHA_SHORT }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from:
            type=registry,ref=${{ env.GIT_BASE }}/${{
            env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:buildcache
          cache-to:
            type=registry,ref=${{ env.GIT_BASE }}/${{
            env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:buildcache,mode=max

  test:
    name: Test unitario
    needs: ["build"]
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15.5-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        # necesario porque el contenedor de postgres no proporciona
        # una verificación de estado
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Verificación
        uses: actions/checkout@v4

      - name: Inyectar slug/ Variables cortas
        uses: rlespinasse/github-slug-action@v4

      - name: Instalar Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login al Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ejecuta test Odoo
        continue-on-error: true
        run: |
          docker pull ${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:sha-${{ env.GITHUB_SHA_SHORT }}
          docker run -e RUN_TESTS -e LOG_LEVEL -e EXTRA_MODULES -e PGHOST --network="host" --name odoo -t ${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:sha-${{ env.GITHUB_SHA_SHORT }}
        env:
          RUN_TESTS: "1"
          LOG_LEVEL: test
          EXTRA_MODULES: base
          PGHOST: localhost

  push:
    name: Empuja a todos los registry
    needs: ["build", "test"]
    runs-on: ubuntu-latest
    steps:
      - name: Verificación local
        uses: actions/checkout@v4

      - name: Inyectar slug/ Variables cortas
        uses: rlespinasse/github-slug-action@v4

        # Gestión automática de etiquetas y especificación de formato de imagen OCI para etiquetas
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # lista de imágenes de Docker para usar como nombre base para las etiquetas
          images: |
            ${{ env.GIT_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
            ${{ env.HUB_BASE }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}

      - name: Instala QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Instalar Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login al Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construye y empuja la imagen
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from:
            type=registry,ref=${{ env.GIT_BASE }}/${{
            env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:buildcache
          cache-to:
            type=registry,ref=${{ env.GIT_BASE }}/${{
            env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:buildcache,mode=max
