#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function

import os
import shutil
import stat
import subprocess
import sys
from argparse import ArgumentParser
from tempfile import NamedTemporaryFile, mkstemp

from andamiolib import logger

# Define opciones de CLI
parser = ArgumentParser(
    description="Ejecute algun codigo en el entorno QA de este contenedor."
)
parser.add_argument(
    "script",
    help="El codigo fuente que se ejecutara. Deberia comenzar con un shebang.",
)
parser.add_argument(
    "arguments", nargs="*", help="Argumentos adicionales pasados al script."
)
args = parser.parse_args()

# Copia el codigo fuente a un archivo ejecutable
executable = NamedTemporaryFile(mode="w+", delete=False)
with executable as tmp:
    logger.debug("Fuente de script interno code:\n%s", args.script)
    tmp.write(args.script)
os.chmod(
    executable.name,
    stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH,
)

# Ejecuta el script
cmd = [executable.name] + args.arguments
returncode = 0
try:
    logger.debug("Ejecutando %r", cmd)
    subprocess.check_call(
        cmd,
        stdout=sys.stderr,
        # TODO Cambiar a text=True cuando solo admitimos Python 3.7+
        universal_newlines=True,
    )
except subprocess.CalledProcessError as error:
    logger.debug("Excepcion de subcomando:", exc_info=True)
    returncode = error.returncode
finally:
    logger.debug("Borrando %s", executable.name)
    os.unlink(executable.name)

    artifacts_zip_path = mkstemp()[1]
    logger.debug("Comprimiento /qa/artifacts en %s.zip", artifacts_zip_path)
    shutil.make_archive(artifacts_zip_path, "zip", "/qa/artifacts")
    artifacts_zip_path += ".zip"
    with open(artifacts_zip_path, "rb") as zip_fd:
        if sys.version_info >= (3,):
            with os.fdopen(sys.stdout.fileno(), "wb", closefd=False) as stdout:
                stdout.write(zip_fd.read())
                stdout.flush()
        # TODO Eliminar al soltar el soporte para Python 2 (Odoo 10.0 y
        # versiones anteriores), ya que esta es una forma menos segura e
        # idiomática de hacer lo mismo que arriba
        else:
            os.write(sys.stdout.fileno(), zip_fd.read())

    logger.debug("Eliminando %s", artifacts_zip_path)
    os.unlink(artifacts_zip_path)

sys.exit(returncode)
